id: 4-DeleteEnvironment
namespace: meteorite

tasks:
  - id: delete_gcs_files
    type: io.kestra.plugin.gcp.gcs.DeleteList
    from: "gs://{{kv('GCP_BUCKET_NAME')}}"
    
  - id: delete_gcs_bucket
    type: io.kestra.plugin.gcp.gcs.DeleteBucket
    name: "{{kv('GCP_BUCKET_NAME')}}"

  - id: delete_bq_dataset
    type: io.kestra.plugin.gcp.bigquery.DeleteDataset
    name: "{{kv('GCP_DATASET')}}"
    deleteContents: true

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"